stages:
  - deploy

variables:
  DEPLOY_HOST: your.vps.ip.address
  DEPLOY_USER: your-vps-user
  DEPLOY_DIR: /docker_projects/deno-server

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - rsync -av --delete ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR

    - ssh $DEPLOY_USER@$DEPLOY_HOST "
        cd $DEPLOY_DIR &&
        docker-compose down &&
        docker-compose up -d --build
      "
  only:
    - main