stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build -t deno-server-image:latest .
    - docker push deno-server-image:latest
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker pull deno-server-image:latest && docker stop deno-server || true && docker rm deno-server || true && docker run -d
