openapi: 3.0.0
info:
  title: EnviroSense API
  version: 1.0.0
  description: API documentation for the EnviroSense project.

servers:
  - url: http://localhost:8101
    description: Local Development Server
  - url: http://94.130.75.173:8101
    description: Deployed API Server