openapi: 3.0.0
info:
  title: EnviroSense API
  version: 1.0.0
  description: API documentation for the EnviroSense project.

servers:
  - url: http://localhost:8101
    description: Local development server

paths:
  /rooms:
    get:
      summary: Retrieve a list of rooms
      description: Fetches all available rooms.
      responses:
        '200':
          description: A list of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /buildings:
    get:
      summary: Retrieve a list of buildings
      description: Fetches all available buildings.
      responses:
        '200':
          description: A list of buildings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Building'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /room-types:
    get:
      summary: Retrieve a list of room types
      description: Fetches all available room types.
      responses:
        '200':
          description: A list of room types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomType'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      summary: Create a new room type
      description: Adds a new room type to the system.
      requestBody:
        description: Room type object that needs to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomType'
      responses:
        '201':
          description: Room type created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomType'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /room-types/{roomTypeDocumentId}:
    get:
      summary: Retrieve a specific room type
      description: Fetches a room type by its document ID.
      parameters:
        - in: path
          name: roomTypeDocumentId
          required: true
          schema:
            type: string
          description: The document ID of the room type
      responses:
        '200':
          description: Room type details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomType'
        '404':
          description: Room type not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      summary: Delete a room type
      description: Removes a room type by its document ID.
      parameters:
        - in: path
          name: roomTypeDocumentId
          required: true
          schema:
            type: string
          description: The document ID of the room type
      responses:
        '204':
          description: Room type deleted successfully
        '404':
          description: Room type not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    put:
      summary: Update a room type
      description: Updates an existing room type by its document ID.
      parameters:
        - in: path
          name: roomTypeDocumentId
          required: true
          schema:
            type: string
          description: The document ID of the room type
      requestBody:
        description: Updated room type object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoomType'
      responses:
        '200':
          description: Room type updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomType'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Room type not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /device-data:
    get:
      summary: Retrieve device data
      description: Fetches data from devices.
      responses:
        '200':
          description: Device data retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeviceData'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: string
          example: "room-123"
        name:
          type: string
          example: "Conference Room A"
        capacity:
          type: integer
          example: 20

    Building:
      type: object
      properties:
        id:
          type: string
          example: "building-456"
        name:
          type: string
          example: "Main Office"
        address:
          type: string
          example: "1234 Elm Street, Springfield, IL"

    RoomType:
      type: object
      properties:
        id:
          type: string
          example: "type-789"
        name:
          type: string
          example: "Lecture Hall"
        description:
          type: string
          example: "A large room suitable for lectures and presentations."

    DeviceData:
      type: object
      properties:
        deviceId:
          type: string
          example: "device-001"
        temperature:
          type: number
          format: float
          example: 23.5
        humidity:
          type: number
          format: float
          example: 45.2
        timestamp:
          type: string
          format: date-time
          example: "2023-10-01T12:34:56Z"